Bookers/config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'books' => 'books#index', as: 'books'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  post 'books' => 'books#create'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@book = Book.new
  	@books = Book.all
  end

  def show
  	@book = Book.find(params[:id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def create
  	@book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
    	redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'books/index'
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render 'books/edit'
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
    flash[:notice] = "Book was successfully destroyed"
  	redirect_to books_path
  end




  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
	<div class="error_explanatation">
		<h4><%= @book.errors.count %> errors prohibited this book from being saved:</h4>

		<ul>
		<% @book.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

<%= form_for(@book, url: "/books/#{@book.id}") do |f| %>

	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<div>
		<%= f.submit 'Update Book' %>
	</div>

<% end %>

<P><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></P>

Bookers/app/views/books/index.html.erb
<h1>Books</h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to 'Show', book_path(book) %></td>
			<td><%= link_to 'Edit', edit_book_path(book) %></td>
			<td><%= link_to 'Destroy', destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<h1>New Book</h1>
<% if @book.errors.any? %>
	<div class="error_explanatation">
		<h4><%= @book.errors.count %> errors prohibited this book from being saved:</h4>

		<ul>
		<% @book.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>
<%= form_for(@book, url: '/books') do |f| %>

	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<div>
		<%= f.submit 'Create Book' %>
	</div>

<% end %>

Bookers/app/views/books/show.html.erb
<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %> </p>

<P><%= link_to "Edit", edit_book_path(@book) %> | <%= link_to "Back", books_path %></P>

Bookers/app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>